# Generated by Django 4.2.6 on 2023-10-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.URLField()),
                ('summary', models.CharField(max_length=100)),
                ('author', models.JSONField(default=dict)),
                ('visibility', models.CharField(max_length=10)),
                ('liked_object', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('uuid', models.URLField(primary_key=True, serialize=False)),
                ('source', models.URLField()),
                ('origin', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.JSONField(default=dict)),
                ('categories', models.JSONField(default=list)),
                ('count', models.IntegerField(default=0)),
                ('comments', models.URLField()),
                ('commentsSrc', models.JSONField(default=dict)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('url_id', models.URLField(primary_key=True, serialize=False)),
                ('author', models.JSONField(default=dict)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.posts')),
            ],
        ),
    ]
