# Generated by Django 4.2.6 on 2023-10-23 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_published_alter_posts_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
