# Generated by Django 4.2.6 on 2023-10-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_posts_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
