# Generated by Django 4.2.6 on 2023-10-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_posts_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sharedWith',
            field=models.JSONField(default=dict),
        ),
    ]
