# Generated by Django 4.2.6 on 2023-10-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='sharedWith',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends-Only'), ('PRIVATE', 'Private')], max_length=10),
        ),
    ]
