# Generated by Django 4.2.6 on 2023-11-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_sharedwith_alter_posts_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='url_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='uuid',
            field=models.CharField(default='temp', max_length=36, serialize=False),
            preserve_default=False,
        ),
    ]
