# Generated by Django 4.2.6 on 2023-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comments_url_id_comments_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(max_length=36, serialize=False),
        ),

    ]
