# Generated by Django 4.2.6 on 2023-11-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_comments_post_alter_comments_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(max_length=36, serialize=False, unique=True, primary_key=True, editable=False)
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(max_length=36, serialize=False, null=True),
        ),
    ]
