# Generated by Django 4.2.6 on 2023-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20231107_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(max_length=36, serialize=False, unique=True, primary_key=True, editable=False),
        ),
    ]
