# Generated by Django 4.2.6 on 2023-11-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20231107_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default='temp', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.posts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
