# Generated by Django 4.2.6 on 2023-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comments_post_alter_comments_uuid_alter_posts_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
