# Generated by Django 4.2.6 on 2023-11-21 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_posts_likecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.AddField(
            model_name='posts',
            name='author_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='author_uuid',
            field=models.CharField(default='temp', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
    ]
