# Generated by Django 4.2.6 on 2023-11-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_posts_author_posts_author_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='author',
        ),
        migrations.AddField(
            model_name='comments',
            name='author_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='author_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='author_uuid',
            field=models.CharField(default='x', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='author_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='author_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='author_uuid',
            field=models.CharField(default='x', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='sharedWith',
            field=models.JSONField(default=list, null=True),
        ),
    ]
