# Generated by Django 4.2.6 on 2023-11-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_comments_author_remove_likes_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='liked_object_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], default='post', max_length=10),
            preserve_default=False,
        ),
    ]
