# Generated by Django 4.2.6 on 2023-11-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_likes_liked_object_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='visibility',
        ),
    ]
