# Generated by Django 4.2.6 on 2023-11-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_posts_author_url_alter_posts_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_url',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author_uuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='author_url',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='likes',
            name='author_uuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_object',
            field=models.URLField(max_length=350),
        ),
    ]
