# Generated by Django 4.2.6 on 2023-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_comments_author_url_alter_comments_author_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends-Only'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], max_length=10),
        ),
    ]
