# Generated by Django 4.2.6 on 2023-11-08 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(default=uuid.UUID("7bdcfebf-6870-461b-b9ff-4f75f938f4e1"), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid'),
            preserve_default=False,
        ),
    ]
