# Generated by Django 4.2.6 on 2023-11-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
