# Generated by Django 4.2.6 on 2023-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.BinaryField(max_length=200),
        ),
    ]
