# Generated by Django 4.2.6 on 2023-10-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoruser',
            name='age',
        ),
        migrations.AddField(
            model_name='authoruser',
            name='github',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoruser',
            name='host',
            field=models.GenericIPAddressField(default='127.0.0.1:8000/'),
        ),
        migrations.AddField(
            model_name='authoruser',
            name='profile_image',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authoruser',
            name='url',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
