# Generated by Django 4.2.6 on 2023-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_authoruser_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
    ]
