# Generated by Django 4.2.6 on 2023-10-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_authoruser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='type',
            field=models.CharField(default='author', max_length=6),
        ),
    ]
