# Generated by Django 4.2.6 on 2023-11-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_authoruser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoruser',
            name='uuid',
            field=models.CharField(default='temp', max_length=36),
            preserve_default=False,
        ),
    ]
