# Generated by Django 4.2.6 on 2023-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_authoruser_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='uuid',
            field=models.CharField(max_length=36, unique=False),
        ),
    ]
