# Generated by Django 4.2.6 on 2023-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_followers_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='url',
            field=models.URLField(default='http://127.0.0.1/8000/<django.db.models.fields.CharField>'),
        ),
    ]
