# Generated by Django 4.2.6 on 2023-11-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_authoruser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequests',
            name='recipient_uuid',
            field=models.CharField(default='temp', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrequests',
            name='requester_uuid',
            field=models.CharField(default='temp', max_length=36),
            preserve_default=False,
        ),
    ]
