# Generated by Django 4.2.6 on 2023-11-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_followrequests_recipient_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='host',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
