# Generated by Django 4.2.6 on 2023-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_authoruser_host_alter_authoruser_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='is_active',
            field=models.BooleanField(default=None),
        ),
    ]
