# Generated by Django 4.2.6 on 2023-11-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_test_alter_authoruser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
