# Generated by Django 4.2.6 on 2023-11-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
