# Generated by Django 4.2.6 on 2023-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistcontroller',
            name='whitelist_enabled',
        ),
        migrations.AddField(
            model_name='whitelistcontroller',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
