# Generated by Django 4.2.6 on 2023-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_whitelistcontroller_whitelist_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistcontroller',
            name='url',
        ),
        migrations.AddField(
            model_name='whitelistcontroller',
            name='whitelist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
