# Generated by Django 4.2.6 on 2023-11-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_whitelistcontroller_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='is_active',
            field=models.BooleanField(default=None),
        ),
    ]
