# Generated by Django 4.2.6 on 2023-11-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_authoruser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelistcontroller',
            options={'verbose_name': 'Whitelist Settings', 'verbose_name_plural': 'Whitelist Settings'},
        ),
        migrations.AlterField(
            model_name='whitelistcontroller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
