# Generated by Django 4.2.6 on 2023-11-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_whitelistcontroller_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistcontroller',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
