# Generated by Django 4.2.6 on 2023-11-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_whitelistcontroller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistcontroller',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
