# Generated by Django 4.2.6 on 2023-11-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_whitelistcontroller_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistcontroller',
            name='test',
        ),
    ]
