# Generated by Django 4.2.6 on 2023-11-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_whitelistcontroller_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistcontroller',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
