# Generated by Django 4.2.6 on 2023-11-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_authoruser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistcontroller',
            name='whitelist_enabled',
            field=models.BooleanField(default=False, verbose_name='Users need approval to register?'),
        ),
    ]
