# Generated by Django 4.2.6 on 2023-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_followrequests_requester_local_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequests',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='host',
            field=models.URLField(default='http://www.chimp-chat.win/'),
        ),
    ]
