# Generated by Django 4.2.6 on 2023-11-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_followrequests_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrequests',
            unique_together={('requester_uuid', 'recipient_uuid')},
        ),
    ]
