# Generated by Django 4.2.6 on 2023-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_followrequests_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='host',
            field=models.URLField(default='https://chimp-chat-1e0cca1cc8ce.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
