# Generated by Django 4.2.6 on 2023-11-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_authoruser_host_alter_authoruser_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='host',
            field=models.URLField(default='https://chimp-chat-1e0cca1cc8ce.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='recipient_uuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='followrequests',
            name='requester_uuid',
            field=models.CharField(max_length=100),
        ),
    ]
