# Generated by Django 4.2.6 on 2023-11-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_authoruser_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('author_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name='authoruser',
            name='host',
            field=models.URLField(default='http://localhost:8000/'),
        ),
    ]
